### ISSUE TITLE
EP and TEASER export of BIM file fail

### ISSUE THREAD

**Issue by FWuellhorst** [BIM2SIM/bim2sim#488]
I have a BIM file and try to export it to TEASER or EP. I can provide full logs or the BIM file if required.

For TEASER, the following error occurs:

```
user>INFO: Export to TEASER
'Material' represents no model and can't be used
[WARNING] bim2sim.kernel.attribute: Unit not set!
dev>2023-02-17 15:33:45,191 [WARNING] bim2sim.kernel.attribute._get_value: Unit not set!
[ERROR] bim2sim.kernel.attribute: Function 0 of <ThermalZone>.net_area raised unsupported operand type(s) for /: 'dict_values' and 'int'
dev>2023-02-17 15:33:45,192 [ERROR] bim2sim.kernel.attribute.get_from_functions: Function 0 of <ThermalZone>.net_area raised unsupported operand type(s) for /: 'dict_values' and 'int'
[WARNING] bim2sim.kernel.attribute: Attribute "net_area" from class "ThermalZone" has no: 
dev>2023-02-17 15:33:45,192 [WARNING] bim2sim.kernel.attribute.get_attribute_dependency: Attribute "net_area" from class "ThermalZone" has no: 
[WARNING] bim2sim.kernel.attribute: - dependant attributes: "horizontal_sbs"
dev>2023-02-17 15:33:45,192 [WARNING] bim2sim.kernel.attribute.get_attribute_dependency: - dependant attributes: "horizontal_sbs"
[ERROR] bim2sim.Playground: Task '<Task (ExportTEASER)>' failed!
Traceback (most recent call last):
  File "D:\01_Projekte\01_PractiCon\bim2sim\bim2sim\task\base.py", line 96, in run_task
    result = yield from task.run(self.workflow, **read_state)
  File "D:\01_Projekte\01_PractiCon\bim2sim\bim2sim\plugins\PluginTEASER\bim2sim_teaser\task\export_teaser.py", line 45, in run
    exported_buildings.append(models.Building(bldg, parent=prj))
  File "D:\01_Projekte\01_PractiCon\bim2sim\bim2sim\plugins\PluginTEASER\bim2sim_teaser\models\__init__.py", line 43, in __init__
    self.add_thermal_zones_to_building()
  File "D:\01_Projekte\01_PractiCon\bim2sim\bim2sim\plugins\PluginTEASER\bim2sim_teaser\models\__init__.py", line 47, in add_thermal_zones_to_building
    ThermalZone(tz, parent=self)
  File "D:\01_Projekte\01_PractiCon\bim2sim\bim2sim\plugins\PluginTEASER\bim2sim_teaser\models\__init__.py", line 65, in __init__
    TEASER.__init__(self, element)
  File "D:\01_Projekte\01_PractiCon\bim2sim\bim2sim\plugins\PluginTEASER\bim2sim_teaser\export\__init__.py", line 40, in __init__
    self.request_params()
  File "D:\01_Projekte\01_PractiCon\bim2sim\bim2sim\plugins\PluginTEASER\bim2sim_teaser\models\__init__.py", line 76, in request_params
    self.request_param("net_area",
  File "D:\01_Projekte\01_PractiCon\bim2sim\bim2sim\plugins\PluginTEASER\bim2sim_teaser\export\__init__.py", line 127, in request_param
    self.element.request(name)
  File "D:\01_Projekte\01_PractiCon\bim2sim\bim2sim\kernel\element.py", line 114, in request
    return self.attributes.request(name, external_decision)
  File "D:\01_Projekte\01_PractiCon\bim2sim\bim2sim\kernel\attribute.py", line 537, in request
    decision = attr.request(self.bind, external_decision)
  File "D:\01_Projekte\01_PractiCon\bim2sim\bim2sim\kernel\attribute.py", line 287, in request
    _decision = self.get_dependency_decisions(
  File "D:\01_Projekte\01_PractiCon\bim2sim\bim2sim\kernel\attribute.py", line 325, in get_dependency_decisions
    bind.request(d_attr)
  File "D:\01_Projekte\01_PractiCon\bim2sim\bim2sim\kernel\element.py", line 114, in request
    return self.attributes.request(name, external_decision)
  File "D:\01_Projekte\01_PractiCon\bim2sim\bim2sim\kernel\attribute.py", line 530, in request
    value, status = self[name]
KeyError: 'horizontal_sbs'
```

For EP, the idf file created, but the simulation fails afterwards:

```
[WARNING] bim2sim.kernel.attribute: Unit not set!
dev>2023-02-17 15:29:27,221 [WARNING] bim2sim.kernel.attribute._get_value: Unit not set!
[WARNING] bim2sim.kernel.attribute: Unit not set!
dev>2023-02-17 15:29:27,271 [WARNING] bim2sim.kernel.attribute._get_value: Unit not set!
[WARNING] bim2sim.kernel.attribute: Unit not set!
dev>2023-02-17 15:29:27,276 [WARNING] bim2sim.kernel.attribute._get_value: Unit not set!
[WARNING] bim2sim.kernel.attribute: Unit not set!
dev>2023-02-17 15:29:27,282 [WARNING] bim2sim.kernel.attribute._get_value: Unit not set!
[WARNING] bim2sim.kernel.attribute: Unit not set!
dev>2023-02-17 15:29:27,309 [WARNING] bim2sim.kernel.attribute._get_value: Unit not set!
[WARNING] bim2sim.kernel.attribute: Unit not set!
dev>2023-02-17 15:29:27,314 [WARNING] bim2sim.kernel.attribute._get_value: Unit not set!
[WARNING] bim2sim.kernel.attribute: Unit not set!
dev>2023-02-17 15:29:27,319 [WARNING] bim2sim.kernel.attribute._get_value: Unit not set!
[INFO] bim2sim.plugins.PluginEnergyPlus.bim2sim_energyplus.task.ep_create_idf: Get predefined materials and construction ...
dev>2023-02-17 15:29:27,331 [INFO] bim2sim.plugins.PluginEnergyPlus.bim2sim_energyplus.task.ep_create_idf.get_preprocessed_materials_and_constructions: Get predefined materials and construction ...
[INFO] bim2sim.plugins.PluginEnergyPlus.bim2sim_energyplus.task.ep_create_idf: Add Shadings ...
dev>2023-02-17 15:29:27,332 [INFO] bim2sim.plugins.PluginEnergyPlus.bim2sim_energyplus.task.ep_create_idf.add_shadings: Add Shadings ...
[INFO] bim2sim.plugins.PluginEnergyPlus.bim2sim_energyplus.task.ep_create_idf: Set Simulation Control ...
dev>2023-02-17 15:29:27,332 [INFO] bim2sim.plugins.PluginEnergyPlus.bim2sim_energyplus.task.ep_create_idf.set_simulation_control: Set Simulation Control ...
[INFO] bim2sim.plugins.PluginEnergyPlus.bim2sim_energyplus.task.ep_create_idf: Export IDF geometry
dev>2023-02-17 15:29:27,333 [INFO] bim2sim.plugins.PluginEnergyPlus.bim2sim_energyplus.task.ep_create_idf.export_geom_to_idf: Export IDF geometry
[INFO] bim2sim.plugins.PluginEnergyPlus.bim2sim_energyplus.task.ep_create_idf: Set ground temperature...
dev>2023-02-17 15:29:27,335 [INFO] bim2sim.plugins.PluginEnergyPlus.bim2sim_energyplus.task.ep_create_idf.set_ground_temperature: Set ground temperature...
[INFO] bim2sim.plugins.PluginEnergyPlus.bim2sim_energyplus.task.ep_create_idf: Set output variables ...
dev>2023-02-17 15:29:27,336 [INFO] bim2sim.plugins.PluginEnergyPlus.bim2sim_energyplus.task.ep_create_idf.set_output_variables: Set output variables ...
[INFO] bim2sim.plugins.PluginEnergyPlus.bim2sim_energyplus.task.ep_create_idf: Start IDF Validity Checker
dev>2023-02-17 15:29:27,339 [INFO] bim2sim.plugins.PluginEnergyPlus.bim2sim_energyplus.task.ep_create_idf.idf_validity_check: Start IDF Validity Checker
[INFO] bim2sim.plugins.PluginEnergyPlus.bim2sim_energyplus.task.ep_create_idf: IDF Validity Checker done
dev>2023-02-17 15:29:27,339 [INFO] bim2sim.plugins.PluginEnergyPlus.bim2sim_energyplus.task.ep_create_idf.idf_validity_check: IDF Validity Checker done
[INFO] bim2sim.plugins.PluginEnergyPlus.bim2sim_energyplus.task.ep_create_idf: Save idf ...
dev>2023-02-17 15:29:27,339 [INFO] bim2sim.plugins.PluginEnergyPlus.bim2sim_energyplus.task.ep_create_idf.run: Save idf ...
[INFO] bim2sim.plugins.PluginEnergyPlus.bim2sim_energyplus.task.ep_create_idf: Idf file successfully saved.
dev>2023-02-17 15:29:27,433 [INFO] bim2sim.plugins.PluginEnergyPlus.bim2sim_energyplus.task.ep_create_idf.run: Idf file successfully saved.
[INFO] bim2sim.Playground: Successfully finished Task '<Task (CreateIdf)>'
dev>2023-02-17 15:29:27,433 [INFO] bim2sim.Playground.run_task: Successfully finished Task '<Task (CreateIdf)>'
[INFO] bim2sim.Playground: <Task (CreateIdf)> done
dev>2023-02-17 15:29:27,433 [INFO] bim2sim.Playground.run_task: <Task (CreateIdf)> done
[INFO] bim2sim.Playground: Starting Task '<Task (IdfPostprocessing)>'
dev>2023-02-17 15:29:27,433 [INFO] bim2sim.Playground.run_task: Starting Task '<Task (IdfPostprocessing)>'
[INFO] bim2sim.task.base.IdfPostprocessing: IDF Postprocessing started...
user>INFO: IDF Postprocessing started...
D:\01_Projekte\01_PractiCon\bim2sim\bim2sim\plugins\PluginEnergyPlus\bim2sim_energyplus\task\ep_idf_postprocessing.py:91: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  space_df = space_df.append([
D:\01_Projekte\01_PractiCon\bim2sim\bim2sim\plugins\PluginEnergyPlus\bim2sim_energyplus\task\ep_idf_postprocessing.py:91: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  space_df = space_df.append([
D:\01_Projekte\01_PractiCon\bim2sim\bim2sim\plugins\PluginEnergyPlus\bim2sim_energyplus\task\ep_idf_postprocessing.py:91: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  space_df = space_df.append([
D:\01_Projekte\01_PractiCon\bim2sim\bim2sim\plugins\PluginEnergyPlus\bim2sim_energyplus\task\ep_idf_postprocessing.py:91: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  space_df = space_df.append([
D:\01_Projekte\01_PractiCon\bim2sim\bim2sim\plugins\PluginEnergyPlus\bim2sim_energyplus\task\ep_idf_postprocessing.py:91: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  space_df = space_df.append([
D:\01_Projekte\01_PractiCon\bim2sim\bim2sim\plugins\PluginEnergyPlus\bim2sim_energyplus\task\ep_idf_postprocessing.py:91: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  space_df = space_df.append([
D:\01_Projekte\01_PractiCon\bim2sim\bim2sim\plugins\PluginEnergyPlus\bim2sim_energyplus\task\ep_idf_postprocessing.py:91: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  space_df = space_df.append([
D:\01_Projekte\01_PractiCon\bim2sim\bim2sim\plugins\PluginEnergyPlus\bim2sim_energyplus\task\ep_idf_postprocessing.py:121: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  bound_count = bound_count.append([
[INFO] bim2sim.task.base.IdfPostprocessing: IDF Postprocessing finished!
user>INFO: IDF Postprocessing finished!
[INFO] bim2sim.Playground: Successfully finished Task '<Task (IdfPostprocessing)>'
dev>2023-02-17 15:29:27,468 [INFO] bim2sim.Playground.run_task: Successfully finished Task '<Task (IdfPostprocessing)>'
[INFO] bim2sim.Playground: <Task (IdfPostprocessing)> done
dev>2023-02-17 15:29:27,468 [INFO] bim2sim.Playground.run_task: <Task (IdfPostprocessing)> done
[INFO] bim2sim.Playground: Starting Task '<Task (ExportIdfForCfd)>'
dev>2023-02-17 15:29:27,468 [INFO] bim2sim.Playground.run_task: Starting Task '<Task (ExportIdfForCfd)>'
[INFO] bim2sim.Playground: Successfully finished Task '<Task (ExportIdfForCfd)>'
dev>2023-02-17 15:29:27,469 [INFO] bim2sim.Playground.run_task: Successfully finished Task '<Task (ExportIdfForCfd)>'
[INFO] bim2sim.Playground: <Task (ExportIdfForCfd)> done
dev>2023-02-17 15:29:27,469 [INFO] bim2sim.Playground.run_task: <Task (ExportIdfForCfd)> done
[INFO] bim2sim.Playground: Starting Task '<Task (RunEnergyPlusSimulation)>'
dev>2023-02-17 15:29:27,469 [INFO] bim2sim.Playground.run_task: Starting Task '<Task (RunEnergyPlusSimulation)>'

C:\EnergyPlusV9-4-0\energyplus.exe --weather D:\01_Projekte\01_PractiCon\bim2sim\bim2sim\assets\weatherfiles\DEU_NW_Aachen.105010_TMYx.epw --output-directory D:\01_Projekte\01_PractiCon\bim-models\energyplus\SUM\export\EP-results --design-day --idd C:/EnergyPlusV9-4-0/Energy+.idd --expandobjects --readvars D:\01_Projekte\01_PractiCon\bim2sim\bim2sim\examples\in.idf

ExpandObjects Started.
 Begin reading Energy+.idd file.
 Done reading Energy+.idd file.
ExpandObjects Finished. Time:     0.109
EnergyPlus Starting
EnergyPlus, Version 9.4.0-998c4b761e, YMD=2023.02.17 15:29
Adjusting Air System Sizing
Adjusting Standard 62.1 Ventilation Sizing
Initializing Simulation
Program terminated: EnergyPlus Terminated--Error(s) Detected.
[ERROR] bim2sim.Playground: Task '<Task (RunEnergyPlusSimulation)>' failed!
Traceback (most recent call last):
  File "D:\05_Programme\Anaconda3\envs\pyPractiCon\lib\site-packages\eppy\runner\run_functions.py", line 357, in run
    check_call(cmd)
  File "D:\05_Programme\Anaconda3\envs\pyPractiCon\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\EnergyPlusV9-4-0\\energyplus.exe', '--weather', 'D:\\01_Projekte\\01_PractiCon\\bim2sim\\bim2sim\\assets\\weatherfiles\\DEU_NW_Aachen.105010_TMYx.epw', '--output-directory', 'D:\\01_Projekte\\01_PractiCon\\bim-models\\energyplus\\SUM\\export\\EP-results', '--design-day', '--idd', 'C:/EnergyPlusV9-4-0/Energy+.idd', '--expandobjects', '--readvars', 'D:\\01_Projekte\\01_PractiCon\\bim2sim\\bim2sim\\examples\\in.idf']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\01_Projekte\01_PractiCon\bim2sim\bim2sim\task\base.py", line 99, in run_task
    result = task.run(self.workflow, **read_state)
  File "D:\01_Projekte\01_PractiCon\bim2sim\bim2sim\plugins\PluginEnergyPlus\bim2sim_energyplus\task\ep_run_simulation.py", line 17, in run
    idf.run(output_directory=output_string, readvars=True, annual=ep_full,
  File "D:\05_Programme\Anaconda3\envs\pyPractiCon\lib\site-packages\eppy\modeleditor.py", line 1014, in run
    run(self, weather=epw, idd=idd, **kwargs)
  File "D:\05_Programme\Anaconda3\envs\pyPractiCon\lib\site-packages\eppy\runner\run_functions.py", line 362, in run
    raise EnergyPlusRunError(message)
eppy.runner.run_functions.EnergyPlusRunError: 

Contents of EnergyPlus error file at D:\01_Projekte\01_PractiCon\bim-models\energyplus\SUM\export\EP-results\eplusout.err
Program Version,EnergyPlus, Version 9.4.0-998c4b761e, YMD=2023.02.17 15:29,
   ** Warning ** Site:GroundTemperature:BuildingSurface: Some values fall outside the range of 15-25C.
   **   ~~~   ** These values may be inappropriate.  Please consult the Input Output Reference for more details.
   ** Warning ** Weather file location will be used rather than entered (IDF) Location object.
   **   ~~~   ** ..Location object=DENVER_STAPLETON_CO_USA_WMO_724690
   **   ~~~   ** ..Weather File Location=Aachen NW DEU ISD-TMYx WMO#=105010
   **   ~~~   ** ..due to location differences, Latitude difference=[11.03] degrees, Longitude difference=[110.89] degrees.
   **   ~~~   ** ..Time Zone difference=[8.0] hour(s), Elevation difference=[85.60] percent, [1379.00] meters.
   ** Warning ** SetUpDesignDay: Entered DesignDay Barometric Pressure=83411 differs by more than 10% from Standard Barometric Pressure=98569.
   **   ~~~   ** ...occurs in DesignDay=DENVER_STAPLETON ANN HTG 99.6% CONDNS DB, Standard Pressure (based on elevation) will be used.
   ** Severe  ** GetSurfaceData: Zone has no surfaces, Zone=0M0J9ZACB0L9QP0CV2UQX1
   ** Severe  ** GetSurfaceData: Zone has no surfaces, Zone=0M0J9ZACB0L9QP0CV2UQX2
   ** Severe  ** GetSurfaceData: Zone has no surfaces, Zone=0M0J9ZACB0L9QP0CV2UQZX
   ** Severe  ** GetSurfaceData: Zone has no surfaces, Zone=3SN9LEDSL0LGEHM$8UH$ZY
   ** Severe  ** GetSurfaceData: Zone has no surfaces, Zone=3F06A7MK592XMKYPFL1O3J
   ** Severe  ** GetSurfaceData: Zone has no surfaces, Zone=3F06A7MK592XMKYPFL1OYD
   ** Severe  ** GetSurfaceData: Zone has no surfaces, Zone=3F06A7MK592XMKYPFL1OYW
   **  Fatal  ** GetSurfaceData: Errors discovered, program terminates.
   ...Summary of Errors that led to program termination:
   ..... Reference severe error count=7
   ..... Last severe error=GetSurfaceData: Zone has no surfaces, Zone=3F06A7MK592XMKYPFL1OYW
   ************* Warning:  Node connection errors not checked - most system input has not been read (see previous warning).
   ************* Fatal error -- final processing.  Program exited before simulations began.  See previous error messages.
   ************* EnergyPlus Warmup Error Summary. During Warmup: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Sizing Error Summary. During Sizing: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Terminated--Fatal Error Detected. 3 Warning; 7 Severe Errors; Elapsed Time=00hr 00min  0.62sec

dev>2023-02-17 15:29:28,630 [ERROR] bim2sim.Playground.run_task: Task '<Task (RunEnergyPlusSimulation)>' failed!
```

**Comment by veronikarichter** [comment]
Does your IFC file contain IfcRelSpaceBoundary objects? It looks like the EnergyPlus simulation failed due to the fact that the generated zones have no surfaces.
